name: Email Step Demo

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 23f2000254@ds.study.iitm.ac.in
        run: echo "Hello, world!"